{
	"header": {
		"line": "CVE-2021-23017 (A security issue in nginx resolver was identified, which might allow a ...)",
		"name": "CVE-2021-23017",
		"description": "(A security issue in nginx resolver was identified, which might allow a ...)"
	},
	"annotations": [
		{
			"line": "\t{DSA-4921-1 DLA-2670-1}",
			"type": "xref",
			"bugs": [
				"DSA-4921-1",
				"DLA-2670-1"
			]
		},
		{
			"line": "\t- nginx 1.18.0-6.1 (bug #989095)",
			"type": "package",
			"package": "nginx",
			"kind": "fixed",
			"version": "1.18.0-6.1",
			"flags": [
				{
					"bug": 989095
				}
			]
		},
		{
			"line": "\tNOTE: https://www.openwall.com/lists/oss-security/2021/05/25/5",
			"type": "NOTE",
			"description": "https://www.openwall.com/lists/oss-security/2021/05/25/5"
		},
		{
			"line": "\tNOTE: Patch: http://nginx.org/download/patch.2021.resolver.txt",
			"type": "NOTE",
			"description": "Patch: http://nginx.org/download/patch.2021.resolver.txt"
		},
		{
			"line": "\tNOTE: Fixed by: https://github.com/nginx/nginx/commit/7199ebc203f74fd9e44595474de6bdc41740c5cf (1.20.1)",
			"type": "NOTE",
			"description": "Fixed by: https://github.com/nginx/nginx/commit/7199ebc203f74fd9e44595474de6bdc41740c5cf (1.20.1)"
		}
	]
}
