{
	"header": {
		"line": "CVE-2021-20228 (A flaw was found in the Ansible Engine 2.9.18, where sensitive info is ...)",
		"name": "CVE-2021-20228",
		"description": "(A flaw was found in the Ansible Engine 2.9.18, where sensitive info is ...)"
	},
	"annotations": [
		{
			"line": "\t{DSA-4950-1}",
			"type": "xref",
			"bugs": [
				"DSA-4950-1"
			]
		},
		{
			"line": "\t- ansible 2.10.7+merged+base+2.10.8+dfsg-1",
			"type": "package",
			"package": "ansible",
			"kind": "fixed",
			"version": "2.10.7+merged+base+2.10.8+dfsg-1"
		},
		{
			"line": "\t[stretch] - ansible <end-of-life> (EOL'd for stretch)",
			"type": "package",
			"release": "stretch",
			"package": "ansible",
			"kind": "end-of-life",
			"description": "EOL'd for stretch"
		},
		{
			"line": "\t- ansible-base <removed>",
			"type": "package",
			"package": "ansible-base",
			"kind": "removed"
		},
		{
			"line": "\tNOTE: https://bugzilla.redhat.com/show_bug.cgi?id=1925002",
			"type": "NOTE",
			"description": "https://bugzilla.redhat.com/show_bug.cgi?id=1925002"
		},
		{
			"line": "\tNOTE: https://github.com/ansible/ansible/pull/73487",
			"type": "NOTE",
			"description": "https://github.com/ansible/ansible/pull/73487"
		}
	]
}
