{
	"header": {
		"line": "CVE-2021-20191 (A flaw was found in ansible. Credentials, such as secrets, are being d ...)",
		"name": "CVE-2021-20191",
		"description": "(A flaw was found in ansible. Credentials, such as secrets, are being d ...)"
	},
	"annotations": [
		{
			"line": "\t{DLA-3695-1}",
			"type": "xref",
			"bugs": [
				"DLA-3695-1"
			]
		},
		{
			"line": "\t- ansible 5.4.0-1 (bug #985753)",
			"type": "package",
			"package": "ansible",
			"kind": "fixed",
			"version": "5.4.0-1",
			"flags": [
				{
					"bug": 985753
				}
			]
		},
		{
			"line": "\t[bullseye] - ansible <not-affected> (vulnerable code not present)",
			"type": "package",
			"release": "bullseye",
			"package": "ansible",
			"kind": "not-affected",
			"description": "vulnerable code not present"
		},
		{
			"line": "\t[stretch] - ansible <end-of-life> (EOL'd for stretch)",
			"type": "package",
			"release": "stretch",
			"package": "ansible",
			"kind": "end-of-life",
			"description": "EOL'd for stretch"
		},
		{
			"line": "\tNOTE: https://bugzilla.redhat.com/show_bug.cgi?id=1916813",
			"type": "NOTE",
			"description": "https://bugzilla.redhat.com/show_bug.cgi?id=1916813"
		},
		{
			"line": "\tNOTE: https://github.com/ansible-collections/cisco.nxos/pull/227",
			"type": "NOTE",
			"description": "https://github.com/ansible-collections/cisco.nxos/pull/227"
		},
		{
			"line": "\tNOTE: https://github.com/ansible-collections/cisco.nxos/commit/120956963f47502151a358e4a7bc2a87f71813aa",
			"type": "NOTE",
			"description": "https://github.com/ansible-collections/cisco.nxos/commit/120956963f47502151a358e4a7bc2a87f71813aa"
		}
	]
}
