{
	"header": {
		"line": "CVE-2021-43668 (Go-Ethereum 1.10.9 nodes crash (denial of service) after receiving a s ...)",
		"name": "CVE-2021-43668",
		"description": "(Go-Ethereum 1.10.9 nodes crash (denial of service) after receiving a s ...)"
	},
	"annotations": [
		{
			"line": "\t- golang-github-go-ethereum <itp> (bug #890541)",
			"type": "package",
			"package": "golang-github-go-ethereum",
			"kind": "itp",
			"flags": [
				{
					"bug": 890541
				}
			]
		},
		{
			"line": "\tNOTE: https://github.com/ethereum/go-ethereum/issues/23866",
			"type": "NOTE",
			"description": "https://github.com/ethereum/go-ethereum/issues/23866"
		}
	]
}
