{
	"header": {
		"line": "CVE-2019-19524 (In the Linux kernel before 5.3.12, there is a use-after-free bug that  ...)",
		"name": "CVE-2019-19524",
		"description": "(In the Linux kernel before 5.3.12, there is a use-after-free bug that  ...)"
	},
	"annotations": [
		{
			"line": "\t{DLA-2114-1 DLA-2068-1}",
			"type": "xref",
			"bugs": [
				"DLA-2114-1",
				"DLA-2068-1"
			]
		},
		{
			"line": "\t- linux 5.3.15-1",
			"type": "package",
			"package": "linux",
			"kind": "fixed",
			"version": "5.3.15-1"
		},
		{
			"line": "\t[buster] - linux 4.19.87-1",
			"type": "package",
			"release": "buster",
			"package": "linux",
			"kind": "fixed",
			"version": "4.19.87-1"
		},
		{
			"line": "\t[stretch] - linux 4.9.210-1",
			"type": "package",
			"release": "stretch",
			"package": "linux",
			"kind": "fixed",
			"version": "4.9.210-1"
		},
		{
			"line": "\tNOTE: https://git.kernel.org/linus/fa3a5a1880c91bb92594ad42dfe9eedad7996b86",
			"type": "NOTE",
			"description": "https://git.kernel.org/linus/fa3a5a1880c91bb92594ad42dfe9eedad7996b86"
		}
	]
}
