{
	"header": {
		"line": "CVE-2017-2592 (python-oslo-middleware before versions 3.8.1, 3.19.1, 3.23.1 is vulner ...)",
		"name": "CVE-2017-2592",
		"description": "(python-oslo-middleware before versions 3.8.1, 3.19.1, 3.23.1 is vulner ...)"
	},
	"annotations": [
		{
			"line": "\t- python-oslo.middleware 3.19.0-3 (bug #852742)",
			"type": "package",
			"package": "python-oslo.middleware",
			"kind": "fixed",
			"version": "3.19.0-3",
			"flags": [
				{
					"bug": 852742
				}
			]
		},
		{
			"line": "\tNOTE: https://launchpad.net/bugs/1628031",
			"type": "NOTE",
			"description": "https://launchpad.net/bugs/1628031"
		}
	]
}
