{
	"header": {
		"line": "CVE-2017-9500 (In ImageMagick 7.0.5-8 Q16, an assertion failure was found in the func ...)",
		"name": "CVE-2017-9500",
		"description": "(In ImageMagick 7.0.5-8 Q16, an assertion failure was found in the func ...)"
	},
	"annotations": [
		{
			"line": "\t{DSA-4019-1 DLA-1785-1 DLA-1000-1}",
			"type": "xref",
			"bugs": [
				"DSA-4019-1",
				"DLA-1785-1",
				"DLA-1000-1"
			]
		},
		{
			"line": "\t- imagemagick 8:6.9.7.4+dfsg-13 (low; bug #867778)",
			"type": "package",
			"package": "imagemagick",
			"kind": "fixed",
			"version": "8:6.9.7.4+dfsg-13",
			"flags": [
				{
					"severity": "low"
				},
				{
					"bug": 867778
				}
			]
		},
		{
			"line": "\tNOTE: https://github.com/ImageMagick/ImageMagick/issues/500",
			"type": "NOTE",
			"description": "https://github.com/ImageMagick/ImageMagick/issues/500"
		},
		{
			"line": "\tNOTE: Fixed by: https://github.com/ImageMagick/ImageMagick/commit/5d95b4c24a964114e2b1ae85c2b36769251ed11d",
			"type": "NOTE",
			"description": "Fixed by: https://github.com/ImageMagick/ImageMagick/commit/5d95b4c24a964114e2b1ae85c2b36769251ed11d"
		},
		{
			"line": "\tNOTE: Fixed by (6.x): https://github.com/ImageMagick/ImageMagick/commit/837085e7725f6eb591eb019e299c1ddcf34b9a79",
			"type": "NOTE",
			"description": "Fixed by (6.x): https://github.com/ImageMagick/ImageMagick/commit/837085e7725f6eb591eb019e299c1ddcf34b9a79"
		}
	]
}
