{
	"header": {
		"line": "CVE-2024-56378 (libpoppler.so in Poppler through 24.12.0 has an out-of-bounds read vul ...)",
		"name": "CVE-2024-56378",
		"description": "(libpoppler.so in Poppler through 24.12.0 has an out-of-bounds read vul ...)"
	},
	"annotations": [
		{
			"line": "\t- poppler <unfixed> (bug #1091322)",
			"type": "package",
			"package": "poppler",
			"kind": "unfixed",
			"flags": [
				{
					"bug": 1091322
				}
			]
		},
		{
			"line": "\t[bookworm] - poppler <no-dsa> (Minor issue)",
			"type": "package",
			"release": "bookworm",
			"package": "poppler",
			"kind": "no-dsa",
			"description": "Minor issue"
		},
		{
			"line": "\tNOTE: https://gitlab.freedesktop.org/poppler/poppler/-/issues/1553",
			"type": "NOTE",
			"description": "https://gitlab.freedesktop.org/poppler/poppler/-/issues/1553"
		},
		{
			"line": "\tNOTE: https://gitlab.freedesktop.org/poppler/poppler/-/commit/ade9b5ebed44b0c15522c27669ef6cdf93eff84e",
			"type": "NOTE",
			"description": "https://gitlab.freedesktop.org/poppler/poppler/-/commit/ade9b5ebed44b0c15522c27669ef6cdf93eff84e"
		}
	]
}
