{
	"header": {
		"line": "CVE-2024-8418 (A flaw was found in Aardvark-dns versions 1.12.0 and 1.12.1. They cont ...)",
		"name": "CVE-2024-8418",
		"description": "(A flaw was found in Aardvark-dns versions 1.12.0 and 1.12.1. They cont ...)"
	},
	"annotations": [
		{
			"line": "\t- aardvark-dns 1.12.2-1 (bug #1080964)",
			"type": "package",
			"package": "aardvark-dns",
			"kind": "fixed",
			"version": "1.12.2-1",
			"flags": [
				{
					"bug": 1080964
				}
			]
		},
		{
			"line": "\tNOTE: https://github.com/containers/aardvark-dns/issues/500",
			"type": "NOTE",
			"description": "https://github.com/containers/aardvark-dns/issues/500"
		},
		{
			"line": "\tNOTE: https://github.com/containers/aardvark-dns/pull/503",
			"type": "NOTE",
			"description": "https://github.com/containers/aardvark-dns/pull/503"
		},
		{
			"line": "\tNOTE: https://github.com/containers/aardvark-dns/commit/6d76c50978755b8162d176ec7eea0e09f8d57a42",
			"type": "NOTE",
			"description": "https://github.com/containers/aardvark-dns/commit/6d76c50978755b8162d176ec7eea0e09f8d57a42"
		},
		{
			"line": "\tNOTE: https://github.com/containers/aardvark-dns/commit/39d0043c306c936fb5b6480b456cc1fdec869e25",
			"type": "NOTE",
			"description": "https://github.com/containers/aardvark-dns/commit/39d0043c306c936fb5b6480b456cc1fdec869e25"
		}
	]
}
