{
	"header": {
		"line": "CVE-2020-16092 (In QEMU through 5.0.0, an assertion failure can occur in the network p ...)",
		"name": "CVE-2020-16092",
		"description": "(In QEMU through 5.0.0, an assertion failure can occur in the network p ...)"
	},
	"annotations": [
		{
			"line": "\t{DSA-4760-1 DLA-2373-1}",
			"type": "xref",
			"bugs": [
				"DSA-4760-1",
				"DLA-2373-1"
			]
		},
		{
			"line": "\t- qemu 1:5.1+dfsg-1",
			"type": "package",
			"package": "qemu",
			"kind": "fixed",
			"version": "1:5.1+dfsg-1"
		},
		{
			"line": "\tNOTE: https://bugzilla.redhat.com/show_bug.cgi?id=1860283",
			"type": "NOTE",
			"description": "https://bugzilla.redhat.com/show_bug.cgi?id=1860283"
		},
		{
			"line": "\tNOTE: https://git.qemu.org/?p=qemu.git;a=commit;h=035e69b063835a5fd23cacabd63690a3d84532a8",
			"type": "NOTE",
			"description": "https://git.qemu.org/?p=qemu.git;a=commit;h=035e69b063835a5fd23cacabd63690a3d84532a8"
		}
	]
}
