{
	"header": {
		"line": "CVE-2020-14422 (Lib/ipaddress.py in Python through 3.8.3 improperly computes hash valu ...)",
		"name": "CVE-2020-14422",
		"description": "(Lib/ipaddress.py in Python through 3.8.3 improperly computes hash valu ...)"
	},
	"annotations": [
		{
			"line": "\t{DLA-3424-1 DLA-2280-1}",
			"type": "xref",
			"bugs": [
				"DLA-3424-1",
				"DLA-2280-1"
			]
		},
		{
			"line": "\t- python3.8 3.8.4~rc1-1",
			"type": "package",
			"package": "python3.8",
			"kind": "fixed",
			"version": "3.8.4~rc1-1"
		},
		{
			"line": "\t- python3.7 <removed>",
			"type": "package",
			"package": "python3.7",
			"kind": "removed"
		},
		{
			"line": "\t[buster] - python3.7 3.7.3-2+deb10u2",
			"type": "package",
			"release": "buster",
			"package": "python3.7",
			"kind": "fixed",
			"version": "3.7.3-2+deb10u2"
		},
		{
			"line": "\t- python3.5 <removed>",
			"type": "package",
			"package": "python3.5",
			"kind": "removed"
		},
		{
			"line": "\t- python3.4 <removed>",
			"type": "package",
			"package": "python3.4",
			"kind": "removed"
		},
		{
			"line": "\t[jessie] - python3.4 <postponed> (Minor issue, DoS with constraints)",
			"type": "package",
			"release": "jessie",
			"package": "python3.4",
			"kind": "postponed",
			"description": "Minor issue, DoS with constraints"
		},
		{
			"line": "\t- python2.7 <not-affected> (ipaddress module introduced in 3.3)",
			"type": "package",
			"package": "python2.7",
			"kind": "not-affected",
			"description": "ipaddress module introduced in 3.3"
		},
		{
			"line": "\t- python-ipaddress <removed>",
			"type": "package",
			"package": "python-ipaddress",
			"kind": "removed"
		},
		{
			"line": "\t[bullseye] - python-ipaddress <no-dsa> (Minor issue)",
			"type": "package",
			"release": "bullseye",
			"package": "python-ipaddress",
			"kind": "no-dsa",
			"description": "Minor issue"
		},
		{
			"line": "\tNOTE: https://bugs.python.org/issue41004",
			"type": "NOTE",
			"description": "https://bugs.python.org/issue41004"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/pull/20956",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/pull/20956"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/pull/21033",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/pull/21033"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/commit/b30ee26e366bf509b7538d79bfec6c6d38d53f28 (master)",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/commit/b30ee26e366bf509b7538d79bfec6c6d38d53f28 (master)"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/commit/9a646aa82dfa62d70ca2a99ada901ee6cf9f82bd (3.9-branch)",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/commit/9a646aa82dfa62d70ca2a99ada901ee6cf9f82bd (3.9-branch)"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/commit/dc8ce8ead182de46584cc1ed8a8c51d48240cbd5 (v3.8.4rc1)",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/commit/dc8ce8ead182de46584cc1ed8a8c51d48240cbd5 (v3.8.4rc1)"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/commit/b98e7790c77a4378ec4b1c71b84138cb930b69b7 (3.7-branch)",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/commit/b98e7790c77a4378ec4b1c71b84138cb930b69b7 (3.7-branch)"
		},
		{
			"line": "\tNOTE: https://github.com/python/cpython/commit/cfc7ff8d05f7a949a88b8a8dd506fb5c1c30d3e9 (3.6-branch)",
			"type": "NOTE",
			"description": "https://github.com/python/cpython/commit/cfc7ff8d05f7a949a88b8a8dd506fb5c1c30d3e9 (3.6-branch)"
		}
	]
}
