{
	"header": {
		"line": "CVE-2020-10684 (A flaw was found in Ansible Engine, all versions 2.7.x, 2.8.x and 2.9. ...)",
		"name": "CVE-2020-10684",
		"description": "(A flaw was found in Ansible Engine, all versions 2.7.x, 2.8.x and 2.9. ...)"
	},
	"annotations": [
		{
			"line": "\t{DSA-4950-1}",
			"type": "xref",
			"bugs": [
				"DSA-4950-1"
			]
		},
		{
			"line": "\t- ansible 2.9.7+dfsg-1",
			"type": "package",
			"package": "ansible",
			"kind": "fixed",
			"version": "2.9.7+dfsg-1"
		},
		{
			"line": "\t[stretch] - ansible <end-of-life> (EOL'd for stretch)",
			"type": "package",
			"release": "stretch",
			"package": "ansible",
			"kind": "end-of-life",
			"description": "EOL'd for stretch"
		},
		{
			"line": "\tNOTE: https://bugzilla.redhat.com/show_bug.cgi?id=1815519",
			"type": "NOTE",
			"description": "https://bugzilla.redhat.com/show_bug.cgi?id=1815519"
		},
		{
			"line": "\tNOTE: https://github.com/ansible/ansible/pull/68431",
			"type": "NOTE",
			"description": "https://github.com/ansible/ansible/pull/68431"
		},
		{
			"line": "\tNOTE: https://github.com/ansible/ansible/commit/a9d2ceafe429171c0e2ad007058b88bae57c74ce",
			"type": "NOTE",
			"description": "https://github.com/ansible/ansible/commit/a9d2ceafe429171c0e2ad007058b88bae57c74ce"
		}
	]
}
