{
	"header": {
		"line": "CVE-2020-14402 (An issue was discovered in LibVNCServer before 0.9.13. libvncserver/co ...)",
		"name": "CVE-2020-14402",
		"description": "(An issue was discovered in LibVNCServer before 0.9.13. libvncserver/co ...)"
	},
	"annotations": [
		{
			"line": "\t{DLA-2347-1 DLA-2264-1}",
			"type": "xref",
			"bugs": [
				"DLA-2347-1",
				"DLA-2264-1"
			]
		},
		{
			"line": "\t- libvncserver 0.9.13+dfsg-1",
			"type": "package",
			"package": "libvncserver",
			"kind": "fixed",
			"version": "0.9.13+dfsg-1"
		},
		{
			"line": "\t[buster] - libvncserver 0.9.11+dfsg-1.3+deb10u4",
			"type": "package",
			"release": "buster",
			"package": "libvncserver",
			"kind": "fixed",
			"version": "0.9.11+dfsg-1.3+deb10u4"
		},
		{
			"line": "\tNOTE: https://github.com/LibVNC/libvncserver/commit/74e8a70f2c9a5248d6718ce443e07c7ed314dfff",
			"type": "NOTE",
			"description": "https://github.com/LibVNC/libvncserver/commit/74e8a70f2c9a5248d6718ce443e07c7ed314dfff"
		}
	]
}
